### PR TITLE
KEYCLOAK-15516 Update the image to UBI 8.2

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.redhat.com/browse/KEYCLOAK-15516

See https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.2&container-tabs=gti&gti-tabs=unauthenticated

### CODE REVIEW

**Comment by rsenthilnathan25** [comment]
Any idea, when this will be merged into master?

**Comment by slaskawi** [comment]
Let me close this PR. Actually leaving it as is is more flexible. We don't need to use a specific tag here.

**Comment by rsenthilnathan25** [comment]
I thought this was going to fix the below vulnerability,

https://access.redhat.com/errata/RHSA-2020:3658

**Comment by slaskawi** [comment]
This one has already been fixed. Please check the rebuilt images.

**Comment by rsenthilnathan25** [comment]
It still shows up in our image scan. I'm using jboss/keycloak:latest image. The image was built 2 weeks ago and I believe the Red Hat package was released last week.

**Comment by stianst** [comment]
Seems Docker Hub didn't build the images last time. Triggered rebuild now.

**Comment by rsenthilnathan25** [comment]
Thanks, the latest image is fine.

**Pull request closed without merging**
