### PR TITLE
Update docker-entrypoint.sh

### PR DESCRIPTION
**Pull request by ypyf**
Fix 'append_port_db_addr: command not found'.

### CODE REVIEW

**Comment by abstractj** [comment]
@ypyf thanks for taking the time submitting this. Could you please take a look at our [contributing guidelines](https://github.com/jboss-dockerfiles/keycloak/blob/master/CONTRIBUTING.md)?

If there's a bug, please file a Jira with the steps to reproduce. Also, make sure your commit has the same Jira id.

**Comment by geowrian** [comment]
A bug for this issue was reported on 8/27:
https://issues.jboss.org/browse/KEYCLOAK-11212

**Comment by geowrian** [comment]
> 
> 
> @ypyf please see my comments on https://issues.jboss.org/browse/KEYCLOAK-11212. If you managed to provide the steps to reproduce the issue, I'd really appreciate.

Ticket updated. Looks like the issue does not exist in the "latest" tag, but still exists in 7.0.0 tag in the docker repo (https://hub.docker.com/r/jboss/keycloak/tags).

**Comment by abstractj** [comment]
> Ticket updated. Looks like the issue may or may not exist in the "latest" tag, but does exists in 7.0.0 tag in the docker repo (https://hub.docker.com/r/jboss/keycloak/tags).

@geowrian @ypyf I just tried the command below and couldn't find any issues:

```
docker run --name keycloak --net keycloak-network -e DB_USER=keycloak -e DB_PASSWORD=password -e DB_PORT=1111 -e DB_ADDR=127.0.0.1 keycloak/keycloak:7.0.0
```

Could you please confirm? I'm afraid to say that this PR is superseded by the latest changes. But I'd appreciate your confirmation.

**Comment by geowrian** [comment]
> @geowrian @ypyf I just tried the command below and couldn't find any issues:
> 
> ```
> docker run --name keycloak --net keycloak-network -e DB_USER=keycloak -e DB_PASSWORD=password -e DB_PORT=1111 -e DB_ADDR=127.0.0.1 keycloak/keycloak:7.0.0
> ```
> 
> Could you please confirm? I'm afraid to say that this PR is superseded by the latest changes. But I'd appreciate your confirmation.

I am seeing the error still with that command. It appears at the very top of the log.

```
docker run --name keycloak -e DB_USER=keycloak -e DB_PASSWORD=password -e DB_PORT=1111 -e DB_ADDR=127.0.0.1 -e DB_VENDOR=postgres -e POSTGRES_PORT=1111 -e DB_DATABASE=db -e DB_SCHEMA=keycloak jboss/keycloak
-b 0.0.0.0
/opt/jboss/tools/docker-entrypoint.sh: line 138: append_port_db_addr: command not found
```

I am not running a local postgres server on any port. My understanding is the consequence of the error is that it fails to append the port information and therefore uses the default. Our configuration runs postgres on a non-default port. We also don't run it

**Comment by tfluehmann** [comment]
When is this fix going to be released?

**Comment by Simbaclaws** [comment]
Apparently if you use the openshift example with https located here:
https://github.com/keycloak/keycloak-containers/blob/master/openshift-examples/keycloak-https.json

The docker image returns an error and gets stuck in a Crash Loop Back-off when using any database other then H2 for production purposes.

The error is as followed:
/opt/jboss/tools/docker-entrypoint.sh: line 165: DB_ADDR: unbound variable

I'm guessing that the openshift-example doesn't have a DB_ADDR variable set whenever you use POSTGRES as DB_VENDOR.

Only H2 as a database engine seems to work.
MYSQL and MARIADB fails to connect to the database with a different error message shown below.
```
13:25:35,377 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0403: Unexpected failure during execution of the following operation(s): [{
    "address" => [
        ("core-service" => "management"),
        ("security-realm" => "ManagementRealm")
    ],
    "operation" => "add",
    "map-groups-to-roles" => false
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("security-realm" => "ManagementRealm"),
        ("authentication" => "local")
    ],
    "default-user" => "$local",
    "skip-group-loading" => true
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("security-realm" => "ManagementRealm"),
        ("authentication" => "properties")
    ],
    "path" => "mgmt-users.properties",
    "relative-to" => "jboss.server.config.dir"
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("security-realm" => "ManagementRealm"),
        ("authorization" => "properties")
    ],
    "path" => "mgmt-groups.properties",
    "relative-to" => "jboss.server.config.dir"
}, {
    "address" => [
        ("core-service" => "management"),
        ("security-realm" => "ApplicationRealm")
    ],
    "operation" => "add"
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("security-realm" => "ApplicationRealm"),
        ("server-identity" => "ssl")
    ],
    "keystore-path" => "application.keystore",
    "keystore-relative-to" => "jboss.server.config.dir",
    "keystore-password" => "password",
    "alias" => "server",
    "key-password" => "password",
    "generate-self-signed-certificate-host" => "localhost"
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("security-realm" => "ApplicationRealm"),
        ("authentication" => "local")
    ],
    "default-user" => "$local",
    "allowed-users" => "*",
    "skip-group-loading" => true
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("security-realm" => "ApplicationRealm"),
        ("authentication" => "properties")
    ],
    "path" => "application-users.properties",
    "relative-to" => "jboss.server.config.dir"
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("security-realm" => "ApplicationRealm"),
        ("authorization" => "properties")
    ],
    "path" => "application-roles.properties",
    "relative-to" => "jboss.server.config.dir"
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("access" => "audit")
    ]
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("access" => "audit"),
        ("json-formatter" => "json-formatter")
    ]
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("access" => "audit"),
        ("file-handler" => "file")
    ],
    "formatter" => "json-formatter",
    "path" => "audit-log.log",
    "relative-to" => "jboss.server.data.dir"
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("access" => "audit"),
        ("logger" => "audit-log")
    ],
    "log-boot" => true,
    "log-read-only" => false,
    "enabled" => false
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("access" => "audit"),
        ("logger" => "audit-log"),
        ("handler" => "file")
    ]
}, {
    "operation" => "add",
    "address" => [
        ("core-service" => "management"),
        ("management-interface" => "http-interface")
    ],
    "security-realm" => "ManagementRealm",
    "http-upgrade" => {"enabled" => true},
    "socket-binding" => "management-http"
}, {
    "operation" => "write-attribute",
    "address" => [
        ("core-service" => "management"),
        ("access" => "authorization")
    ],
    "name" => "provider",
    "value" => "simple"
}, {
    "address" => [
        ("core-service" => "management"),
        ("access" => "authorization"),
        ("role-mapping" => "SuperUser")
    ],
    "operation" => "add"
}, {
    "operation" => "add",
    "type" => "user",
    "name" => "$local",
    "address" => [
        ("core-service" => "management"),
        ("access" => "authorization"),
        ("role-mapping" => "SuperUser"),
        ("include" => "user-$local")
    ]
}, {
    "address" => [("interface" => "management")],
    "operation" => "add",
    "inet-address" => expression "${jboss.bind.address.management:127.0.0.1}"
}, {
    "address" => [("interface" => "private")],
    "operation" => "add",
    "inet-address" => expression "${jboss.bind.address.private:127.0.0.1}"
}, {
    "address" => [("interface" => "public")],
    "operation" => "add",
    "inet-address" => expression "${jboss.bind.address:127.0.0.1}"
}, {
    "operation" => "add",
    "address" => [("socket-binding-group" => "standard-sockets")],
    "default-interface" => "public",
    "port-offset" => expression "${jboss.socket.binding.port-offset:0}"
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "ajp")
    ],
    "operation" => "add",
    "port" => expression "${jboss.ajp.port:8009}"
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "http")
    ],
    "operation" => "add",
    "port" => expression "${jboss.http.port:8080}"
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "https")
    ],
    "operation" => "add",
    "port" => expression "${jboss.https.port:8443}"
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "jgroups-mping")
    ],
    "operation" => "add",
    "interface" => "private",
    "multicast-address" => expression "${jboss.default.multicast.address:230.0.0.4}",
    "multicast-port" => 45700
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "jgroups-tcp")
    ],
    "operation" => "add",
    "interface" => "private",
    "port" => 7600
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "jgroups-tcp-fd")
    ],
    "operation" => "add",
    "interface" => "private",
    "port" => 57600
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "jgroups-udp")
    ],
    "operation" => "add",
    "interface" => "private",
    "port" => 55200,
    "multicast-address" => expression "${jboss.default.multicast.address:230.0.0.4}",
    "multicast-port" => 45688
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "jgroups-udp-fd")
    ],
    "operation" => "add",
    "interface" => "private",
    "port" => 54200
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "management-http")
    ],
    "operation" => "add",
    "interface" => "management",
    "port" => expression "${jboss.management.http.port:9990}"
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "management-https")
    ],
    "operation" => "add",
    "interface" => "management",
    "port" => expression "${jboss.management.https.port:9993}"
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "modcluster")
    ],
    "operation" => "add",
    "multicast-address" => expression "${jboss.modcluster.multicast.address:224.0.1.105}",
    "multicast-port" => 23364
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "txn-recovery-environment")
    ],
    "operation" => "add",
    "port" => 4712
}, {
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("socket-binding" => "txn-status-manager")
    ],
    "operation" => "add",
    "port" => 4713
}, {
    "operation" => "add",
    "host" => expression "${jboss.mail.server.host:localhost}",
    "port" => expression "${jboss.mail.server.port:25}",
    "address" => [
        ("socket-binding-group" => "standard-sockets"),
        ("remote-destination-outbound-socket-binding" => "mail-smtp")
    ]
}, {
    "operation" => "parallel-subsystem-boot",
    "address" => []
}, {
    "operation" => "add",
    "address" => [("subsystem" => "logging")]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "logging"),
        ("pattern-formatter" => "PATTERN")
    ],
    "pattern" => "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "logging"),
        ("pattern-formatter" => "COLOR-PATTERN")
    ],
    "pattern" => "%K{level}%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "logging"),
        ("console-handler" => "CONSOLE")
    ],
    "named-formatter" => "COLOR-PATTERN"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "logging"),
        ("logger" => "com.arjuna")
    ],
    "level" => "WARN"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "logging"),
        ("logger" => "io.jaegertracing.Configuration")
    ],
    "level" => "WARN"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "logging"),
        ("logger" => "org.jboss.as.config")
    ],
    "level" => "DEBUG"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "logging"),
        ("logger" => "sun.rmi")
    ],
    "level" => "WARN"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "logging"),
        ("logger" => "org.keycloak")
    ],
    "level" => expression "${env.KEYCLOAK_LOGLEVEL:INFO}"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "logging"),
        ("root-logger" => "ROOT")
    ],
    "level" => expression "${env.ROOT_LOGLEVEL:INFO}",
    "handlers" => ["CONSOLE"]
}, {
    "operation" => "add",
    "address" => [("subsystem" => "bean-validation")]
}, {
    "operation" => "add",
    "address" => [("subsystem" => "core-management")]
}, {
    "operation" => "add",
    "address" => [("subsystem" => "datasources")]
}, {
    "operation" => "add",
    "jndi-name" => "java:jboss/datasources/ExampleDS",
    "enabled" => true,
    "use-java-context" => true,
    "statistics-enabled" => expression "${wildfly.datasources.statistics-enabled:${wildfly.statistics-enabled:false}}",
    "address" => [
        ("subsystem" => "datasources"),
        ("data-source" => "ExampleDS")
    ],
    "connection-url" => "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
    "driver-name" => "h2",
    "user-name" => "sa",
    "password" => "sa"
}, {
    "operation" => "add",
    "jndi-name" => "java:jboss/datasources/KeycloakDS",
    "enabled" => true,
    "use-java-context" => true,
    "use-ccm" => true,
    "address" => [
        ("subsystem" => "datasources"),
        ("data-source" => "KeycloakDS")
    ],
    "connection-url" => expression "jdbc:mariadb://${env.DB_ADDR:mariadb}:${env.DB_PORT:3306}/${env.DB_DATABASE:keycloak}${env.JDBC_PARAMS:}",
    "driver-name" => "mariadb",
    "flush-strategy" => "IdleConnections",
    "user-name" => expression "${env.DB_USER:keycloak}",
    "password" => expression "${env.DB_PASSWORD:password}",
    "check-valid-connection-sql" => "SELECT 1",
    "background-validation" => true,
    "background-validation-millis" => 60000L
}, {
    "operation" => "add",
    "driver-name" => "h2",
    "driver-major-version" => undefined,
    "driver-minor-version" => undefined,
    "driver-module-name" => "com.h2database.h2",
    "address" => [
        ("subsystem" => "datasources"),
        ("jdbc-driver" => "h2")
    ],
    "driver-xa-datasource-class-name" => "org.h2.jdbcx.JdbcDataSource"
}, {
    "operation" => "add",
    "driver-name" => "mariadb",
    "driver-major-version" => undefined,
    "driver-minor-version" => undefined,
    "driver-module-name" => "org.mariadb.jdbc",
    "address" => [
        ("subsystem" => "datasources"),
        ("jdbc-driver" => "mariadb")
    ],
    "driver-xa-datasource-class-name" => "org.mariadb.jdbc.MySQLDataSource"
}, {
    "operation" => "add",
    "address" => [("subsystem" => "deployment-scanner")]
}, {
    "operation" => "add",
    "path" => "deployments",
    "relative-to" => "jboss.server.base.dir",
    "scan-interval" => 5000,
    "runtime-failure-causes-rollback" => expression "${jboss.deployment.scanner.rollback.on.failure:false}",
    "address" => [
        ("subsystem" => "deployment-scanner"),
        ("scanner" => "default")
    ]
}, {
    "operation" => "add",
    "address" => [("subsystem" => "ee")],
    "spec-descriptor-property-replacement" => false
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ee"),
        ("context-service" => "default")
    ],
    "jndi-name" => "java:jboss/ee/concurrency/context/default",
    "use-transaction-setup-provider" => true
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ee"),
        ("managed-thread-factory" => "default")
    ],
    "jndi-name" => "java:jboss/ee/concurrency/factory/default",
    "context-service" => "default"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ee"),
        ("managed-executor-service" => "default")
    ],
    "jndi-name" => "java:jboss/ee/concurrency/executor/default",
    "context-service" => "default",
    "hung-task-threshold" => 60000L,
    "keepalive-time" => 5000L
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ee"),
        ("managed-scheduled-executor-service" => "default")
    ],
    "jndi-name" => "java:jboss/ee/concurrency/scheduler/default",
    "context-service" => "default",
    "hung-task-threshold" => 60000L,
    "keepalive-time" => 3000L
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ee"),
        ("service" => "default-bindings")
    ],
    "context-service" => "java:jboss/ee/concurrency/context/default",
    "datasource" => "java:jboss/datasources/ExampleDS",
    "managed-executor-service" => "java:jboss/ee/concurrency/executor/default",
    "managed-scheduled-executor-service" => "java:jboss/ee/concurrency/scheduler/default",
    "managed-thread-factory" => "java:jboss/ee/concurrency/factory/default"
}, {
    "operation" => "add",
    "address" => [("subsystem" => "ejb3")],
    "default-slsb-instance-pool" => "slsb-strict-max-pool",
    "default-stateful-bean-access-timeout" => 5000L,
    "default-sfsb-cache" => "distributable",
    "default-sfsb-passivation-disabled-cache" => "simple",
    "default-singleton-bean-access-timeout" => 5000L,
    "default-security-domain" => "other",
    "default-missing-method-permissions-deny-access" => true,
    "statistics-enabled" => expression "${wildfly.ejb3.statistics-enabled:${wildfly.statistics-enabled:false}}",
    "log-system-exceptions" => true
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("strict-max-bean-instance-pool" => "mdb-strict-max-pool")
    ],
    "derive-size" => "from-cpu-count",
    "timeout" => 5L,
    "timeout-unit" => "MINUTES"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("strict-max-bean-instance-pool" => "slsb-strict-max-pool")
    ],
    "derive-size" => "from-worker-pools",
    "timeout" => 5L,
    "timeout-unit" => "MINUTES"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("cache" => "simple")
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("cache" => "distributable")
    ],
    "passivation-store" => "infinispan",
    "aliases" => [
        "passivating",
        "clustered"
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("passivation-store" => "infinispan")
    ],
    "cache-container" => "ejb",
    "max-size" => 10000
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("service" => "async")
    ],
    "thread-pool-name" => "default"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("service" => "timer-service")
    ],
    "thread-pool-name" => "default",
    "default-data-store" => "default-file-store"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("service" => "timer-service"),
        ("file-data-store" => "default-file-store")
    ],
    "path" => "timer-service-data",
    "relative-to" => "jboss.server.data.dir"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("service" => "remote")
    ],
    "cluster" => "ejb",
    "connectors" => ["http-remoting-connector"],
    "thread-pool-name" => "default"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("service" => "remote"),
        ("channel-creation-options" => "MAX_OUTBOUND_MESSAGES")
    ],
    "value" => "1234",
    "type" => "remoting"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "ejb3"),
        ("thread-pool" => "default")
    ],
    "max-threads" => 10,
    "keepalive-time" => {
        "time" => 60L,
        "unit" => "SECONDS"
    }
}, {
    "operation" => "add",
    "address" => [("subsystem" => "elytron")],
    "final-providers" => "combined-providers",
    "disallowed-providers" => ["OracleUcrypto"]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("aggregate-providers" => "combined-providers")
    ],
    "providers" => [
        "elytron",
        "openssl"
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("provider-loader" => "elytron")
    ],
    "module" => "org.wildfly.security.elytron"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("provider-loader" => "openssl")
    ],
    "module" => "org.wildfly.openssl"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("file-audit-log" => "local-audit")
    ],
    "path" => "audit.log",
    "relative-to" => "jboss.server.log.dir",
    "format" => "JSON"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("security-domain" => "ApplicationDomain")
    ],
    "default-realm" => "ApplicationRealm",
    "permission-mapper" => "default-permission-mapper",
    "realms" => [
        {
            "realm" => "ApplicationRealm",
            "role-decoder" => "groups-to-roles"
        },
        {"realm" => "local"}
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("security-domain" => "ManagementDomain")
    ],
    "default-realm" => "ManagementRealm",
    "permission-mapper" => "default-permission-mapper",
    "realms" => [
        {
            "realm" => "ManagementRealm",
            "role-decoder" => "groups-to-roles"
        },
        {
            "realm" => "local",
            "role-mapper" => "super-user-mapper"
        }
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("identity-realm" => "local")
    ],
    "identity" => "$local"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("properties-realm" => "ApplicationRealm")
    ],
    "users-properties" => {
        "path" => "application-users.properties",
        "relative-to" => "jboss.server.config.dir",
        "digest-realm-name" => "ApplicationRealm"
    },
    "groups-properties" => {
        "path" => "application-roles.properties",
        "relative-to" => "jboss.server.config.dir"
    }
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("properties-realm" => "ManagementRealm")
    ],
    "users-properties" => {
        "path" => "mgmt-users.properties",
        "relative-to" => "jboss.server.config.dir",
        "digest-realm-name" => "ManagementRealm"
    },
    "groups-properties" => {
        "path" => "mgmt-groups.properties",
        "relative-to" => "jboss.server.config.dir"
    }
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("simple-permission-mapper" => "default-permission-mapper")
    ],
    "mapping-mode" => "first",
    "permission-mappings" => [
        {
            "principals" => ["anonymous"],
            "permission-sets" => [{"permission-set" => "default-permissions"}]
        },
        {
            "match-all" => true,
            "permission-sets" => [
                {"permission-set" => "login-permission"},
                {"permission-set" => "default-permissions"}
            ]
        }
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("constant-realm-mapper" => "local")
    ],
    "realm-name" => "local"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("simple-role-decoder" => "groups-to-roles")
    ],
    "attribute" => "groups"
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("constant-role-mapper" => "super-user-mapper")
    ],
    "roles" => ["SuperUser"]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("permission-set" => "login-permission")
    ],
    "permissions" => [{"class-name" => "org.wildfly.security.auth.permission.LoginPermission"}]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("permission-set" => "default-permissions")
    ],
    "permissions" => [
        {
            "class-name" => "org.wildfly.extension.batch.jberet.deployment.BatchPermission",
            "module" => "org.wildfly.extension.batch.jberet",
            "target-name" => "*"
        },
        {
            "class-name" => "org.wildfly.transaction.client.RemoteTransactionPermission",
            "module" => "org.wildfly.transaction.client"
        },
        {
            "class-name" => "org.jboss.ejb.client.RemoteEJBPermission",
            "module" => "org.jboss.ejb-client"
        }
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("http-authentication-factory" => "management-http-authentication")
    ],
    "security-domain" => "ManagementDomain",
    "http-server-mechanism-factory" => "global",
    "mechanism-configurations" => [{
        "mechanism-name" => "DIGEST",
        "mechanism-realm-configurations" => [{"realm-name" => "ManagementRealm"}]
    }]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("provider-http-server-mechanism-factory" => "global")
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("sasl-authentication-factory" => "application-sasl-authentication")
    ],
    "sasl-server-factory" => "configured",
    "security-domain" => "ApplicationDomain",
    "mechanism-configurations" => [
        {
            "mechanism-name" => "JBOSS-LOCAL-USER",
            "realm-mapper" => "local"
        },
        {
            "mechanism-name" => "DIGEST-MD5",
            "mechanism-realm-configurations" => [{"realm-name" => "ApplicationRealm"}]
        }
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("sasl-authentication-factory" => "management-sasl-authentication")
    ],
    "sasl-server-factory" => "configured",
    "security-domain" => "ManagementDomain",
    "mechanism-configurations" => [
        {
            "mechanism-name" => "JBOSS-LOCAL-USER",
            "realm-mapper" => "local"
        },
        {
            "mechanism-name" => "DIGEST-MD5",
            "mechanism-realm-configurations" => [{"realm-name" => "ManagementRealm"}]
        }
    ]
}, {
    "operation" => "add",
    "address" => [
        ("subsystem" => "elytron"),
        ("configurable-sasl-server-factory" => "configured")
    ],
    "sasl-server-factory" => "elytron",
    "properties" => {"wil%
    ```

**Comment by slaskawi** [comment]
Could you please create us a JIRA for this? You can assign it to me.

**Comment by Simbaclaws** [comment]
Dear @slaskawi,

I have never worked with jira before and don't know what this is.
Could you please explain to me how I should be doing that?
I'm quite new to the devops world.

**Pull request merged**
