### PR TITLE
KEYCLOAK-17029: skipping directories during autorun.sh

### PR DESCRIPTION
**Pull request by rfelgent**
Hello,

here is the PR for https://issues.redhat.com/browse/KEYCLOAK-17029

### CODE REVIEW

**Comment by rfelgent** [comment]
So far no feedback from KeyClock committer/developer

**Review by slaskawi — APPROVED** [review]
LGTM, let's give @ASzc a day or two to have a look at it.

**Comment by rfelgent** [comment]
Hello,

@ASzc hasnt answered yet.

**Comment by slaskawi** [comment]
@ASzc Could you please have a look at this? I plan to merge this next week.

**Comment by rfelgent** [comment]
Hi @slaskawi,

can you give any updates regarding this pull requests ?

**Comment by slaskawi** [comment]
Integrated, thanks @rfelgent

**Pull request merged**
