### PR TITLE
[KEYCLOAK-11931] [Extensions Init container] Change name and base image

### PR DESCRIPTION
**Pull request by abstractj**
## JIRA ID

[KEYCLOAK-11931](https://issues.jboss.org/browse/KEYCLOAK-11931)

## What
Based on conversations with Stian, the base image for the extensions init container should be changed to ubi-minimal 

https://github.com/pb82/keycloak-containers/blob/932126b10f9e885252b7c1638f52aa448d6ef427/extensions-init-container/Dockerfile

Also the name should be changed to probably to `keycloak-init-container` and also for the quay.io image repo.

### CODE REVIEW

**Comment by abstractj** [comment]
@davidffrench @pb82 could you please review when you get the chance?

**Comment by davidffrench** [comment]
@abstractj What is the status of this PR? Do you think this and a new release of the init container will be done tomorrow?

**Comment by abstractj** [comment]
@davidffrench today I will check with Stian and create the build on quay.io.

**Comment by davidffrench** [comment]
thank you @abstractj

**Pull request merged**
