### PR TITLE
[KEYCLOAK-11622] Make the user/password handling more safe for whitespace

### PR DESCRIPTION
**Pull request by cartmanume**
Make the user/password handling more safe for whitespace in user or password. This wraps them both in ".

### CODE REVIEW

**Comment by stianst** [comment]
@slaskawi could you give this a try please?

**Comment by stianst** [comment]
@cartmanume did you already create a JIRA for this or could you create one?

**Comment by cartmanume** [comment]
> @cartmanume did you already create a JIRA for this or could you create one?

No, but I created one now, not sure if I got all the fields right. :)

**Comment by stianst** [comment]
@cartmanume could you give me the link to the issue you created? I can't find it ;)

**Comment by abstractj** [comment]
@stianst just added to the description, but you can also find it here https://issues.jboss.org/browse/KEYCLOAK-11622

**Comment by stianst** [comment]
@abstractj thanks

**Comment by slaskawi** [comment]
LGTM, thanks for the Pull Request, @cartmanume !

**Pull request merged**
