### PR TITLE
KEYCLOAK-12947 new docker compose example

### PR DESCRIPTION
**Pull request by ERRECabrera**
added a new example to run keycloak in HA mode with postgres database and jdbc_ping discovery protocol

### CODE REVIEW

**Comment by abstractj** [comment]
@ERRECabrera thanks for submitting this, although we need a prior discussion about it on the mailing list, plus a Jira. Could you please check https://github.com/keycloak/keycloak-containers/blob/master/CONTRIBUTING.md ?

**Comment by slaskawi** [comment]
@ERRECabrera @abstractj After thinking about this for a while - perhaps we should have just 1 `JDBC_PING` example (@ERRECabrera it might be refactored to Postgresql, I have no preference here). The idea is to show how it works and adding more than 1 example just increases maintenance burden.

**Comment by slaskawi** [comment]
@abstractj @stianst @ERRECabrera What do you think? Do you guys agree with what I've written?

**Comment by abstractj** [comment]
@slaskawi not sure if you started a thread about this, but that would be a fantastic discussion to the dev mailing list.

**Comment by slaskawi** [comment]
Started discussion on this one: https://groups.google.com/forum/#!topic/keycloak-dev/33EiJbMaxlY

**Pull request merged**
